In [2]:
import pandas as pd
behaviour = pd.read_csv("C:/Users/adith/spotify_analytics/data/cleaned/spotify_user_behavior_cleaned1.csv")
churn = pd.read_csv("C:/Users/adith/spotify_analytics/data/cleaned/spotify_churn_processed.csv")

In [5]:
behaviour.head()

,age,gender,spotify_usage_period,spotify_listening_device,spotify_subscription_plan,premium_sub_willingness,preffered_premium_plan,preferred_listening_content,fav_music_genre,music_time_slot,...,Uses_Radio,Uses_External,music_expl_category,Travel_Listening,Leisure_Listening,Workout_Listening,Study_Listening,Office_Listening,Night_Winddown,pod_lis_category
0,20-35,Female,More than 2 years,Smart speakers or voice assistants,Free,Yes,Family,Podcast,Melody,Night,...,0,0,Playlist-driven,0,1,0,0,0,0,Regular user
1,12-20,Male,More than 2 years,Computer or laptop,Free,Yes,Individual,Podcast,Rap,Afternoon,...,0,0,Playlist-driven,0,0,1,0,0,0,Regular user
2,35-60,Others,6 months to 1 year,Smart speakers or voice assistants,Free,Yes,Student,Podcast,Pop,Night,...,0,0,Playlist-driven,1,0,0,1,0,0,Light user
3,20-35,Female,1 year to 2 years,"Smartphone, Smart speakers or voice assistants",Free,No,No Interest,Music,Melody,Night,...,0,0,Hybrid: Rec + Playlist,0,1,1,0,1,0,Non-podcast user
4,20-35,Female,1 year to 2 years,Smartphone,Free,No,No Interest,Music,Melody,Night,...,0,0,Hybrid: Rec + Playlist,0,1,0,0,0,0,Light user

In [3]:
behaviour['preffered_premium_plan'].unique()

array(['Family', 'Individual', 'Student', 'No Interest', 'Unknown', 'Duo'],
      dtype=object)

In [6]:
audio_features = pd.read_csv("C:/Users/adith/spotify_analytics/data/cleaned/audio_features_cleaned.csv")
spotify_streams = pd.read_csv("C:/Users/adith/spotify_analytics/data/cleaned/spotify_global_streams_processed.csv")

In [7]:
audio_features.head()

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,track_genre
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,acoustic
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,acoustic
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,acoustic
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,acoustic
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,acoustic

In [8]:
spotify_streams.head()

,Country,Artist,Album,Genre,Release Year,Monthly Listeners (Millions),Total Streams (Millions),Total Hours Streamed (Millions),Avg Stream Duration (Min),Platform Type,Streams Last 30 Days (Millions),Skip Rate (%),reach_cohort,Momentum_Category,Hours per Stream,Engagement_Category
0,Germany,Taylor Swift,1989 (Taylor's Version),K-pop,2020,23.10,3695.53,14240.35,4.28,Free,118.51,2.24,Mid-Tier (10–50M),Stable Superstar,3.853399,Loyal Hits
1,Brazil,The Weeknd,After Hours,R&B,2023,60.60,2828.16,11120.44,3.90,Premium,44.87,23.98,Superstar (50M+),Legacy Decliner,3.932041,Polarizing Tracks
2,United States,Post Malone,Austin,Reggaeton,2019,42.84,1425.46,4177.49,4.03,Free,19.46,4.77,Mid-Tier (10–50M),Background Catalog,2.930626,Loyal Hits
3,Italy,Ed Sheeran,Autumn Variations,K-pop,2019,73.24,2704.33,12024.08,3.26,Premium,166.05,25.12,Superstar (50M+),Stable Superstar,4.446233,Weak Engagement
4,Italy,Ed Sheeran,Autumn Variations,R&B,2019,7.89,3323.25,13446.32,4.47,Free,173.43,15.82,Emerging (<10M),Stable Superstar,4.046136,Loyal Hits